name: F0rc3Run Vpn Configs FlowBridge

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ğŸ“¥ Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          repository: F0rc3Run/F0rc3Run
          token: ${{ secrets.PAT }}
          path: final-destination

      - name: ğŸ” Checkout Private Source Repo
        uses: actions/checkout@v4
        with:
          repository: F0rc3Run/vpn-config
          token: ${{ secrets.PAT }}
          path: source-app

      - name: âš™ï¸ Set up Go with Cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.19'
          cache-dependency-path: ./source-app/go.sum

      - name:  caching Xray Core
        id: cache-xray
        uses: actions/cache@v4
        with:
          path: ./source-app/xray
          key: ${{ runner.os }}-xray-core

      - name: ğŸ”½ Download Xray Core
        if: steps.cache-xray.outputs.cache-hit != 'true'
        working-directory: ./source-app
        run: |
          wget -q -O xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o xray.zip xray
          chmod +x xray
          rm xray.zip
      
      - name: ğŸš€ Run Go App to Generate Results
        working-directory: ./source-app
        run: |
          go mod tidy
          go run .

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ğŸ“Š Run Python Script to Split Proxies
        working-directory: ./source-app
        run: python generate_stats.py
      
      - name: ğŸ“‚ Organize Output Files
        run: |
          rm -rf ./final-destination/splitted-by-protocol
          rm -rf ./final-destination/splitted-by-country
          mkdir -p ./final-destination/Best-Results
          mv ./source-app/proxies.txt ./final-destination/Best-Results/
          mv ./source-app/sub.txt ./final-destination/Best-Results/
          mv ./source-app/splitted-by-protocol ./final-destination/
          mv ./source-app/splitted-by-country ./final-destination/
          mv ./source-app/stats.json ./final-destination/Best-Results/
          mv ./source-app/summary.md ./final-destination/
     
      - name: âœ¨ Commit and Push All Changes
        working-directory: ./final-destination
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Update and categorize proxy lists"
            git push
          else
            echo "No changes to commit."
          fi
