name: Generate and Commit V2Ray Configs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: F0rc3Run/vpn-config
          token: ${{ secrets.PAT }}
          path: 'private_repo'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('private_repo/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: pip install -r private_repo/requirements.txt
      
      - name: Install Xray Core
        run: |
          # Ø§Ø¨ØªØ¯Ø§ Ø§Ø³Ú©Ø±ÛŒÙ¾Øª Ø±Ø§ Ø¯Ø± ÙØ§ÛŒÙ„ÛŒ Ø¨Ù‡ Ù†Ø§Ù… install.sh Ø¯Ø§Ù†Ù„ÙˆØ¯ Ú©Ù†
          curl -L -o install.sh https://github.com/XTLS/Xray-core/raw/main/install/install-release.sh
          # Ø¨Ù‡ ÙØ§ÛŒÙ„ Ø¯Ø§Ù†Ù„ÙˆØ¯ Ø´Ø¯Ù‡ Ø¯Ø³ØªØ±Ø³ÛŒ Ø§Ø¬Ø±Ø§ÛŒÛŒ Ø¨Ø¯Ù‡
          chmod +x install.sh
          # Ø§Ø³Ú©Ø±ÛŒÙ¾Øª Ø±Ø§ Ø¨Ø§ Ù¾Ø§Ø±Ø§Ù…ØªØ± install Ø§Ø¬Ø±Ø§ Ú©Ù†
          ./install.sh install

      - name: Prepare Script Files
        run: cp -r private_repo/* .

      - name: Run the Python Script
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add output/all_servers.txt
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ğŸš€ Update server configurations (${{ github.run_number }})"
            git push
          fi
